feat(LinalgOps): FXML-873 add Conv2dTensorAdd((L)Relu)AveragePoolOp compound op
ljfitz/llvm-project pull request #19
Opened 2022-08-05 13:55 UTC by gargaroff

This PR adds fused ops for conv2d_tensoradd_averagepool + relu / leaky relu variants to Linalg.

2022-08-09 07:37 UTC, gargaroff commented
@BraunPhilipp ping :)

2022-08-09 10:38 UTC, BraunPhilipp approved these changes

2022-08-09 10:38 UTC, BraunPhilipp commented on mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp
> +  if (outputShape[2] != 1 || outputShape[3] != 1)
Assert or check the output shape please to avoid accessing non-existent elements.

2022-08-09 12:17 UTC, gargaroff commented on mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp
> +  if (outputShape[2] != 1 || outputShape[3] != 1)
I am doing that already above:

```c++
  int64_t rankI = tensorI.getRank();
  if (rankI != 4)
    return compoundOp.emitOpError("Input tensors must be of rank 4");

  /* ... */

  if (rankI != tensorJ.getRank() || rankI != kernel.getRank() ||
      rankI != output.getRank())
    return compoundOp.emitOpError("Input and output tensor ranks must match");
```

So I check that all input tensors (except the bias) have rank 4, i.e. shape will have 4 elements.

2022-08-09 12:50 UTC, ljfitz requested changes

2022-08-09 12:50 UTC, ljfitz commented on mlir/include/mlir/Dialect/Linalg/IR/LinalgOps.td
> +def Linalg_Conv2dTensorAddReluAveragePoolOp
Probably more a question for @BraunPhilipp - structural-fused ops were added to `mlir/python/mlir/dialects/linalg/opdsl/ops/core_named_ops.py` until now to (mis-)benefit from features for tiling etc. Do we lose/gain anything by expressing them here instead?

2022-08-09 13:01 UTC, gargaroff commented on mlir/include/mlir/Dialect/Linalg/IR/LinalgOps.td
> +def Linalg_Conv2dTensorAddAveragePoolOp
Oh...then this also needs to be fixed on the mlir-xten side. Thanks for pointing it out, I didn't realize there was a difference!

2022-08-09 13:03 UTC, gargaroff commented on mlir/include/mlir/Dialect/Linalg/IR/LinalgOps.td
> +def Linalg_Conv2dTensorAddReluAveragePoolOp
The opinion was that Tablegen is a lot easier to do than to try to make this weird DSL language happy. In hindsight I would not do this again though, since not only is it inconsistent, but also gives the op a different interface...

2022-08-11 08:03 UTC, ljfitz approved these changes

2022-08-11 13:14 UTC, merged