FXML-1037: Subgraph PDL
ljfitz/llvm-project pull request #28
Opened 2022-09-28 14:52 UTC by BraunPhilipp

This PoC is meant as a reference for later PDL implementations. It implements consumer fusion and builds on-top of the `TestPDLByteCodePass`. The pattern driver was modified to disable subgraph op traversal.

**PDL subgraph generation example**

```
func.func @forward(%arg0: tensor<1x3x128x128xf32>) -> tensor<1x3x64x64xf32> {
  %0 = "tosa.const"() {value = dense<[0, 3, 1, 2]> : tensor<4xi32>} : () -> tensor<4xi32>
  %1 = "tosa.const"() {value = dense<[0, 2, 3, 1]> : tensor<4xi32>} : () -> tensor<4xi32>
  %2 = "tosa.const"() {value = dense<1.000000e-01> : tensor<f32>} : () -> tensor<f32>
  %3 = "tosa.const"() {value = dense<0.000000e+00> : tensor<f32>} : () -> tensor<f32>
  %4 = "tosa.greater_equal"(%arg0, %3) : (tensor<1x3x128x128xf32>, tensor<f32>) -> tensor<1x3x128x128xi1>
  %5 = "tosa.mul"(%arg0, %2) {shift = 0 : i32} : (tensor<1x3x128x128xf32>, tensor<f32>) -> tensor<1x3x128x128xf32>
  %6 = "tosa.select"(%4, %arg0, %5) : (tensor<1x3x128x128xi1>, tensor<1x3x128x128xf32>, tensor<1x3x128x128xf32>) -> tensor<1x3x128x128xf32>
  %7 = linalg.subgraph(%arg1 = %6 : tensor<1x3x128x128xf32>, %arg2 = %1 : tensor<4xi32>, %arg3 = %0 : tensor<4xi32>) {
    %8 = linalg.subgraph(%arg4 = %arg1 : tensor<1x3x128x128xf32>, %arg5 = %arg2 : tensor<4xi32>) {
      %10 = "tosa.transpose"(%arg4, %arg5) : (tensor<1x3x128x128xf32>, tensor<4xi32>) -> tensor<1x128x128x3xf32>
      %11 = "tosa.max_pool2d"(%10) {kernel = [2, 2], pad = [0, 0, 0, 0], stride = [2, 2]} : (tensor<1x128x128x3xf32>) -> tensor<1x64x64x3xf32>
      linalg.yield %11 : tensor<1x64x64x3xf32>
    } -> tensor<1x64x64x3xf32>
    %9 = "tosa.transpose"(%8, %arg3) : (tensor<1x64x64x3xf32>, tensor<4xi32>) -> tensor<1x3x64x64xf32>
    linalg.yield %9 : tensor<1x3x64x64xf32>
  } -> tensor<1x3x64x64xf32>
  return %7 : tensor<1x3x64x64xf32>
}
```

2022-09-29 05:56 UTC, gargaroff requested changes
Mostly nits, otherwise looks great. I really like how PDL let's you declare very explicitly but at the same time very simple what you are trying to match and what you want to do with it.

2022-09-29 05:56 UTC, gargaroff commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +/// Collects @p op is used and traverses graph based on the @p root operation
It looks like this function only collects usages that are non-local. Could you update the comment to reflect that?

2022-09-29 05:56 UTC, gargaroff commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +    for (auto &op : region.getOps()) {
Nit: can you use the type name instead of auto? Also I think using a reference goes against the philosophy of MLIR and you should pass by value here instead (depends on the type though, which is why I want you to get rid of the auto 😄)

2022-09-29 05:56 UTC, gargaroff commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +  auto newCaptures = llvm::to_vector(target.captures());
What type is this? Could auto be replaced with the actual type instead?

2022-09-29 05:56 UTC, gargaroff commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +                       captures.lookup(target.captures()[idx]));
Maybe it's still too early for my brain, but I don't fully understand this piece of code. What is this trying to do and why is it looking something up in itself?

2022-09-29 05:56 UTC, gargaroff commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +        // If the old fused op had a result, add it to the mapping.
Nit: fused op was renamed to subgraph

2022-09-29 05:56 UTC, gargaroff commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +  target.erase();
Should we assert in the beginning that target has at most one result? We don't want to accidentally leave something dangling if this assumption ever changes in the future

2022-09-29 05:56 UTC, gargaroff commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +  op->dump();
Leftover debug code?

2022-09-29 05:56 UTC, gargaroff commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +  // subgraphOp->dump();
Leftover debug code?

2022-09-29 05:56 UTC, gargaroff commented on mlir/test/Integration/Dialect/PDL/CPU/subgraph.mlir
> +      // %SUBGRAPH_TWO_OP = pdl.apply_native_rewrite "createSubgraphOp" (%SUBGRAPH_OP : !pdl.operation) : !pdl.operation
Is this leftover test code or on purpose?

2022-09-29 05:56 UTC, gargaroff commented on mlir/test/Integration/Dialect/PDL/CPU/subgraph.mlir
> +      // %SUBGRAPH_TWO_OP = pdl.apply_native_rewrite "createSubgraphOp" (%MAXPOOL_OP : !pdl.operation) : !pdl.operation
Leftover or on purpose?

2022-09-30 03:29 UTC, BraunPhilipp commented on mlir/test/Integration/Dialect/PDL/CPU/subgraph.mlir
> +      // %SUBGRAPH_TWO_OP = pdl.apply_native_rewrite "createSubgraphOp" (%MAXPOOL_OP : !pdl.operation) : !pdl.operation
Updated. Only meant as reference draft PR for later implementations.

2022-09-30 03:29 UTC, BraunPhilipp commented on mlir/test/Integration/Dialect/PDL/CPU/subgraph.mlir
> +      // %SUBGRAPH_TWO_OP = pdl.apply_native_rewrite "createSubgraphOp" (%SUBGRAPH_OP : !pdl.operation) : !pdl.operation
:)

2022-09-30 03:29 UTC, BraunPhilipp commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +  // subgraphOp->dump();
Just cleaned up. Thanks!

2022-09-30 03:29 UTC, BraunPhilipp commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +  op->dump();
~

2022-09-30 03:43 UTC, BraunPhilipp commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +                       captures.lookup(target.captures()[idx]));
We are remapping arguments from the prior subgraph. `target.captures()` or `newCaptures` contains these prior capture ops.

2022-09-30 03:45 UTC, BraunPhilipp commented on mlir/test/lib/Rewrite/TestPDLByteCode.cpp
> +  target.erase();
Good point. Will add an additional assert.

2022-11-08 10:20 UTC, closed without merging